on:
  push:
    tags:
      - 'v*'

name: 🚀 Release

jobs:
  #   publish-to-npm:
  #     name: Publish to npm
  #     runs-on: ubuntu-latest
  #     permissions:
  #       id-token: write
  #     steps:
  #       - name: Checkout source
  #         uses: actions/checkout@v3
  #       - name: setup node
  #         uses: actions/setup-node@v3
  #         with:
  #           node-version: 18
  #           registry-url: 'https://registry.npmjs.org'
  #           cache: npm
  #       - name: Install latest npm version
  #         run: npm i -g npm@latest
  #       - name: Install pnpm
  #         run: npm i -g pnpm@latest
  #       - name: Install dependencies
  #         run: pnpm i
  #       - name: Publish package
  #         run: pnpm publish
  #         env:
  #           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    # needs: publish-to-npm
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        run: gh release create ${{ github.ref }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
